<a href="https://colab.research.google.com/github/wonseokb/Genat4_Study/blob/main/PSD_Scope(raw_data_processing).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tqdm
from tqdm import tqdm
import time

import numpy as np
import os
from google.colab import drive
import matplotlib.pyplot as plt

# Mount the Google Drive to access files
drive.mount('/content/drive')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Mounted at /content/drive


In [ ]:
import numpy as np

# Load the CSV file into a numpy array
Sr_amp_1 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F1Sr9000001.csv', delimiter=',', usecols=(1))
Sr_amp_1 = Sr_amp_1[4:]

Sr_amp_2 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F1Sr9000003.csv', delimiter=',', usecols=(1))
Sr_amp_2 = Sr_amp_2[4:]

Sr_amp_3 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F1Sr9000006.csv', delimiter=',', usecols=(1))
Sr_amp_3 = Sr_amp_3[4:]

Sr_amp_4 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F1Sr9000012.csv', delimiter=',', usecols=(1))
Sr_amp_4 = Sr_amp_4[4:]

Sr_amp_5 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F1Sr9000013.csv', delimiter=',', usecols=(1))
Sr_amp_5 = Sr_amp_5[4:]

Sr_amp_6 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F1Sr9000020.csv', delimiter=',', usecols=(1))
Sr_amp_6 = Sr_amp_6[4:]

Sr_amp_7 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F1Sr9000027.csv', delimiter=',', usecols=(1))
Sr_amp_7 = Sr_amp_7[4:]

Sr_amp_8 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F1Sr9000028.csv', delimiter=',', usecols=(1))
Sr_amp_8 = Sr_amp_8[4:]

Sr_amp_9 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F1Sr9000029.csv', delimiter=',', usecols=(1))
Sr_amp_9 = Sr_amp_9[4:]

# Print the shape of the arrays
print(Sr_amp_1.shape)
print(Sr_amp_2.shape)
print(Sr_amp_3.shape)
print(Sr_amp_4.shape)
print(Sr_amp_5.shape)
print(Sr_amp_6.shape)
print(Sr_amp_7.shape)
print(Sr_amp_8.shape)
print(Sr_amp_9.shape)

# Print the arrays
print(Sr_amp_1)
print(Sr_amp_2)
print(Sr_amp_3)
print(Sr_amp_4)
print(Sr_amp_5)
print(Sr_amp_6)
print(Sr_amp_7)
print(Sr_amp_8)
print(Sr_amp_9)

# Combine the NumPy arrays into one
Sr_amp = np.concatenate((Sr_amp_1, Sr_amp_2, Sr_amp_3, Sr_amp_4, Sr_amp_5, Sr_amp_6, Sr_amp_7, Sr_amp_8, Sr_amp_9))
print(Sr_amp.shape)

(9560,)
(24670,)
(19156,)
(39320,)
(4637,)
(37916,)
(56216,)
(4533,)
(6316,)
[0.0286847 0.0290899 0.0388827 ... 0.0614707 0.02839   0.0361813]
[0.0285825 0.0516815 0.0368873 ... 0.0498782 0.0347896 0.0578764]
[0.0387845 0.0642704 0.0430823 ... 0.0369856 0.0641722 0.0315888]
[0.0514753 0.0344867 0.0368812 ... 0.0529733 0.0561721 0.0333877]
[0.0377835 0.0465797 0.0479788 ... 0.0452791 0.0504765 0.0693695]
[0.0699718 0.0420763 0.0424811 ... 0.0384821 0.0291836 0.0606733]
[0.0434814 0.0610716 0.0401843 ... 0.0474783 0.0429779 0.0290899]
[0.0428797 0.0336824 0.0456794 ... 0.0617715 0.0271866 0.0268858]
[0.0405797 0.0341885 0.0329864 ... 0.0361881 0.0294902 0.0409846]
(202324,)


In [ ]:
import numpy as np

# Load the CSV file into a numpy array
Sr_amp_1 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F1Sr9000001.csv', delimiter=',', usecols=(1))
Sr_amp_1 = Sr_amp_1[4:]

Sr_amp_2 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F1Sr9000003.csv', delimiter=',', usecols=(1))
Sr_amp_2 = Sr_amp_2[4:]

Sr_amp_3 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F1Sr9000006.csv', delimiter=',', usecols=(1))
Sr_amp_3 = Sr_amp_3[4:]

Sr_amp_4 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F1Sr9000012.csv', delimiter=',', usecols=(1))
Sr_amp_4 = Sr_amp_4[4:]

Sr_amp_5 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F1Sr9000013.csv', delimiter=',', usecols=(1))
Sr_amp_5 = Sr_amp_5[4:]

Sr_amp_6 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F1Sr9000020.csv', delimiter=',', usecols=(1))
Sr_amp_6 = Sr_amp_6[4:]

Sr_amp_7 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F1Sr9000027.csv', delimiter=',', usecols=(1))
Sr_amp_7 = Sr_amp_7[4:]

Sr_amp_8 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F1Sr9000028.csv', delimiter=',', usecols=(1))
Sr_amp_8 = Sr_amp_8[4:]

Sr_amp_9 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F1Sr9000029.csv', delimiter=',', usecols=(1))
Sr_amp_9 = Sr_amp_9[4:]

# Print the shape of the arrays
print(Sr_amp_1.shape)
print(Sr_amp_2.shape)
print(Sr_amp_3.shape)
print(Sr_amp_4.shape)
print(Sr_amp_5.shape)
print(Sr_amp_6.shape)
print(Sr_amp_7.shape)
print(Sr_amp_8.shape)
print(Sr_amp_9.shape)

# Print the arrays
print(Sr_amp_1)
print(Sr_amp_2)
print(Sr_amp_3)
print(Sr_amp_4)
print(Sr_amp_5)
print(Sr_amp_6)
print(Sr_amp_7)
print(Sr_amp_8)
print(Sr_amp_9)

# Combine the NumPy arrays into one
Sr_amp = np.concatenate((Sr_amp_1, Sr_amp_2, Sr_amp_3, Sr_amp_4, Sr_amp_5, Sr_amp_6, Sr_amp_7, Sr_amp_8, Sr_amp_9))
print(Sr_amp.shape)

(202324,)


In [ ]:
import numpy as np

# Load the CSV files into numpy arrays and rename variables
area_1 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F2Sr9000001.csv', delimiter=',', usecols=(1))[4:]
area_2 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F2Sr9000003.csv', delimiter=',', usecols=(1))[4:]
area_3 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F2Sr9000006.csv', delimiter=',', usecols=(1))[4:]
area_4 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F2Sr9000012.csv', delimiter=',', usecols=(1))[4:]
area_5 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F2Sr9000013.csv', delimiter=',', usecols=(1))[4:]
area_6 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F2Sr9000020.csv', delimiter=',', usecols=(1))[4:]
area_7 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F2Sr9000027.csv', delimiter=',', usecols=(1))[4:]
area_8 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F2Sr9000028.csv', delimiter=',', usecols=(1))[4:]
area_9 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F2Sr9000029.csv', delimiter=',', usecols=(1))[4:]

# Concatenate the numpy arrays
area = np.concatenate((area_1, area_2, area_3, area_4, area_5, area_6, area_7, area_8, area_9))

# Print the shape of the concatenated array
print(area.shape)

# Print the concatenated array
print(area)


(202324,)
[-4.11765e-10 -4.68750e-10 -5.92157e-10 ... -5.94363e-10 -4.82353e-10
 -6.50490e-10]


In [ ]:
import numpy as np

# Load the CSV files into numpy arrays and rename variables
area_1 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F2Sr9000001.csv', delimiter=',', usecols=(1))[4:]
area_2 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F2Sr9000003.csv', delimiter=',', usecols=(1))[4:]
area_3 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F2Sr9000006.csv', delimiter=',', usecols=(1))[4:]
area_4 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F2Sr9000012.csv', delimiter=',', usecols=(1))[4:]
area_5 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F2Sr9000013.csv', delimiter=',', usecols=(1))[4:]
area_6 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F2Sr9000020.csv', delimiter=',', usecols=(1))[4:]
area_7 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F2Sr9000027.csv', delimiter=',', usecols=(1))[4:]
area_8 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F2Sr9000028.csv', delimiter=',', usecols=(1))[4:]
area_9 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F2Sr9000029.csv', delimiter=',', usecols=(1))[4:]

# Concatenate the numpy arrays
area = np.concatenate((area_1, area_2, area_3, area_4, area_5, area_6, area_7, area_8, area_9))

# Print the shape of the concatenated array
print(area.shape)

# Print the concatenated array
print(area)

(202324,)
[-4.11765e-10 -4.68750e-10 -5.92157e-10 ... -5.94363e-10 -4.82353e-10
 -6.50490e-10]


In [ ]:
import numpy as np

# Load the CSV files into numpy arrays and rename variables
FWHM_1 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F4Sr9000001.csv', delimiter=',', usecols=(1))[4:]
FWHM_2 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F4Sr9000003.csv', delimiter=',', usecols=(1))[4:]
FWHM_3 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F4Sr9000006.csv', delimiter=',', usecols=(1))[4:]
FWHM_4 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F4Sr9000012.csv', delimiter=',', usecols=(1))[4:]
FWHM_5 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F4Sr9000013.csv', delimiter=',', usecols=(1))[4:]
FWHM_6 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F4Sr9000020.csv', delimiter=',', usecols=(1))[4:]
FWHM_7 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F4Sr9000027.csv', delimiter=',', usecols=(1))[4:]
FWHM_8 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F4Sr9000028.csv', delimiter=',', usecols=(1))[4:]
FWHM_9 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F4Sr9000029.csv', delimiter=',', usecols=(1))[4:]

# Concatenate the numpy arrays
FWHM = np.concatenate((FWHM_1, FWHM_2, FWHM_3, FWHM_4, FWHM_5, FWHM_6, FWHM_7, FWHM_8, FWHM_9))

# Print the shape of the concatenated array
print(FWHM.shape)

# Print the concatenated array
print(FWHM)


(202324,)
[1.09760e-08 1.10625e-08 1.05138e-08 ... 1.07812e-08 1.02180e-08
 1.06101e-08]


In [ ]:
import numpy as np

# Load the CSV files into numpy arrays and rename variables
falling_1 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F6Sr9000001.csv', delimiter=',', usecols=(1))[4:]
falling_2 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F6Sr9000003.csv', delimiter=',', usecols=(1))[4:]
falling_3 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F6Sr9000006.csv', delimiter=',', usecols=(1))[4:]
falling_4 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F6Sr9000012.csv', delimiter=',', usecols=(1))[4:]
falling_5 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F6Sr9000013.csv', delimiter=',', usecols=(1))[4:]
falling_6 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F6Sr9000020.csv', delimiter=',', usecols=(1))[4:]
falling_7 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F6Sr9000027.csv', delimiter=',', usecols=(1))[4:]
falling_8 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F6Sr9000028.csv', delimiter=',', usecols=(1))[4:]
falling_9 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F6Sr9000029.csv', delimiter=',', usecols=(1))[4:]

# Concatenate the numpy arrays
falling = np.concatenate((falling_1, falling_2, falling_3, falling_4, falling_5, falling_6, falling_7, falling_8, falling_9))

# Print the shape of the concatenated array
print(falling.shape)

# Print the concatenated array
print(falling)


(202324,)
[2.58594e-09 2.67117e-09 2.45611e-09 ... 2.85141e-09 2.56956e-09
 2.80063e-09]


In [ ]:
import numpy as np

# Load the CSV files into numpy arrays and rename variables
rising_1 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F8Sr9000001.csv', delimiter=',', usecols=(1))[4:]
rising_2 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F8Sr9000003.csv', delimiter=',', usecols=(1))[4:]
rising_3 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F8Sr9000006.csv', delimiter=',', usecols=(1))[4:]
rising_4 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F8Sr9000012.csv', delimiter=',', usecols=(1))[4:]
rising_5 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F8Sr9000013.csv', delimiter=',', usecols=(1))[4:]
rising_6 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F8Sr9000020.csv', delimiter=',', usecols=(1))[4:]
rising_7 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F8Sr9000027.csv', delimiter=',', usecols=(1))[4:]
rising_8 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F8Sr9000028.csv', delimiter=',', usecols=(1))[4:]
rising_9 = np.genfromtxt('/content/drive/My Drive/PSD.Sr/F8Sr9000029.csv', delimiter=',', usecols=(1))[4:]

# Concatenate the numpy arrays
rising = np.concatenate((rising_1, rising_2, rising_3, rising_4, rising_5, rising_6, rising_7, rising_8, rising_9))

# Print the shape of the concatenated array
print(rising.shape)

# Print the concatenated array
print(rising)


(202324,)
[1.19295e-08 1.14716e-08 1.00443e-08 ... 1.17873e-08 1.11607e-08
 1.13750e-08]


In [ ]:
import numpy as np

# Define column names
add_clos = ['amp', 'area', 'FWHM', 'failing', 'rising'] 
# Stack arrays horizontally with column names
add_arrays = [Sr_amp, area, FWHM, falling, rising]
data_array = np.column_stack((add_arrays)).astype(float)

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Convert data_array to a pandas DataFrame
df = pd.DataFrame(data_array, columns = add_clos)

# Save the DataFrame as a CSV file in your Google Drive
file_path = '/content/drive/MyDrive/autoPSD.Sr90-2/PSD - Sr90_200k.csv'
df.to_csv(file_path, index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
